AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  flask-aws-lambda-api

  Sample SAM Template for flask-aws-lambda-api

Globals:
  Function:
    Timeout: 20
    MemorySize: 256

Resources:
  FlaskApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flask-api
      Handler: lambda_handler.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HealthCheckApi:
          Type: Api
          Properties:
            Path: /health
            Method: get
        EmbergaduraApi:
          Type: Api
          Properties:
            Path: /embergadura
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
